name:                pcapp
version:             0.1.0.0
github:              "githubuser/pcap"
license:             BSD3
author:              "Qingbo Liu"
maintainer:          "Quentin.Liu.0415@gmail.com"
copyright:           "2018 Qingbo Liu"
category:            "freeform"
synopsis:            "a parser for offline network packages" 

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/pcap#readme>

dependencies:
- base >= 4.7 && < 5
- binary
- bytestring
- text
- vector 
- vector-algorithms 
- conduit 
- exceptions 
- primitive
- directory 
- resourcet
- cereal 

library:
  source-dirs: src

executables:
  pcap-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pcapp

tests:
  pcap-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pcapp
    - hspec
